import type { Permission } from "#/entity";
import { BaseStatus, PermissionType } from "#/enum";

const staticPermissions: Permission[] = [
	{
		id: 1,
		name: "Home",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.home",
		icon: "solar:home-outline",
		type: PermissionType.MENU,
		route: "home",
		orderValue: 1,
		component: "/home/index.tsx",
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [],
		parentId: null,
	},
	{
		id: 2,
		name: "Sale",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.sale",
		icon: "solar:cart-large-2-outline",
		type: PermissionType.MENU,
		route: "sale",
		orderValue: 2,
		component: "/sale/index.tsx",
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [],
		parentId: null,
	},
	{
		id: 3,
		name: "Products",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.products.index",
		icon: "solar:document-add-linear",
		type: PermissionType.GROUP,
		route: "product",
		orderValue: 3,
		component: null,
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [
			{
				id: 4,
				name: "Add Product",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.products.add",
				icon: null,
				type: PermissionType.MENU,
				route: "add",
				orderValue: 1,
				component: "/products/add/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "3",
			},
			{
				id: 5,
				name: "Edit Product",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.products.edit",
				icon: null,
				type: PermissionType.MENU,
				route: "edit/:id",
				orderValue: 2,
				component: "/products/add/index.tsx",
				frameSrc: null,
				hide: true,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "3",
			},
			{
				id: 6,
				name: "Order Products",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.products.order",
				icon: null,
				type: PermissionType.MENU,
				route: "order",
				orderValue: 3,
				component: "/products/order/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "3",
			},
			{
				id: 7,
				name: "Product List",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.products.list",
				icon: null,
				type: PermissionType.MENU,
				route: "list",
				orderValue: 4,
				component: "/products/list/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "3",
			},
		],
		parentId: null,
	},
	{
		id: 8,
		name: "Categories",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.categories.index",
		icon: "solar:bookmark-circle-outline",
		type: PermissionType.GROUP,
		route: "category",
		orderValue: 4,
		component: null,
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [
			{
				id: 9,
				name: "Add Category",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.categories.add",
				icon: null,
				type: PermissionType.MENU,
				route: "add",
				orderValue: 1,
				component: "/categories/add/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "8",
			},
			{
				id: 10,
				name: "Edit Category",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.categories.edit",
				icon: null,
				type: PermissionType.MENU,
				route: "edit/:id",
				orderValue: 2,
				component: "/categories/add/index.tsx",
				frameSrc: null,
				hide: true,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "8",
			},
			{
				id: 11,
				name: "Order Categories",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.categories.order",
				icon: null,
				type: PermissionType.MENU,
				route: "order",
				orderValue: 3,
				component: "/categories/order/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "8",
			},
			{
				id: 12,
				name: "Category List",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.categories.list",
				icon: null,
				type: PermissionType.MENU,
				route: "list",
				orderValue: 4,
				component: "/categories/list/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "8",
			},
		],
		parentId: null,
	},
	{
		id: 13,
		name: "User Info",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.user.index",
		icon: "solar:user-circle-linear",
		type: PermissionType.GROUP,
		route: "user",
		orderValue: 5,
		component: null,
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [
			{
				id: 14,
				name: "Profile",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.user.profile",
				icon: null,
				type: PermissionType.MENU,
				route: "profile",
				orderValue: 1,
				component: "/management/user/profile/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "13",
			},
			{
				id: 15,
				name: "Account",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.user.account",
				icon: null,
				type: PermissionType.MENU,
				route: "account",
				orderValue: 2,
				component: "/management/user/account/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "13",
			},
		],
		parentId: null,
	},
	{
		id: 16,
		name: "Management",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.management.index",
		icon: "solar:widget-5-bold-duotone",
		type: PermissionType.GROUP,
		route: "management",
		orderValue: 6,
		component: null,
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [
			{
				id: 17,
				name: "Organization",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.management.organization",
				icon: null,
				type: PermissionType.MENU,
				route: "organization",
				orderValue: 1,
				component: "/management/system/organization/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "16",
			},
			{
				id: 18,
				name: "Permission",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.management.permission",
				icon: null,
				type: PermissionType.MENU,
				route: "permission",
				orderValue: 2,
				component: "/management/system/permission/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "16",
			},
			{
				id: 19,
				name: "Role",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.management.role",
				icon: null,
				type: PermissionType.MENU,
				route: "role",
				orderValue: 3,
				component: "/management/system/role/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "16",
			},
			{
				id: 20,
				name: "User",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.management.user",
				icon: null,
				type: PermissionType.MENU,
				route: "user",
				orderValue: 4,
				component: "/management/system/user/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "16",
			},
			{
				id: 21,
				name: "User Detail",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.management.user_detail",
				icon: null,
				type: PermissionType.MENU,
				route: "user/:id",
				orderValue: 5,
				component: "/management/system/user/detail.tsx",
				frameSrc: null,
				hide: true,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "16",
			},
		],
		parentId: null,
	},
	{
		id: 22,
		name: "System",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.system.index",
		icon: "solar:shield-user-outline",
		type: PermissionType.GROUP,
		route: "system",
		orderValue: 7,
		component: null,
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [
			{
				id: 24,
				name: "Sessions",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.system.session",
				icon: null,
				type: PermissionType.MENU,
				route: "session",
				orderValue: 1,
				component: "/system/session/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "22",
			},
			{
				id: 23,
				name: "Logs",
				description: null,
				status: BaseStatus.ENABLE,
				label: "sys.menu.system.log",
				icon: null,
				type: PermissionType.MENU,
				route: "log",
				orderValue: 2,
				component: "/system/log/index.tsx",
				frameSrc: null,
				hide: false,
				hideTab: false,
				newFeature: false,
				children: [],
				parentId: "22",
			},
		],
		parentId: null,
	},
	{
		id: 25,
		name: "Calendar",
		description: null,
		status: BaseStatus.ENABLE,
		label: "sys.menu.calendar",
		icon: "solar:calendar-bold-duotone",
		type: PermissionType.MENU,
		route: "calendar",
		orderValue: 8,
		component: "/system/others/calendar/index.tsx",
		frameSrc: null,
		hide: false,
		hideTab: false,
		newFeature: false,
		children: [],
		parentId: null,
	},
];

export default staticPermissions;
